### ISSUE TITLE
Moved 'Calling client.JoinChannel seems to block joining channels'

### ISSUE THREAD

**Issue by swiftyspiffy** [TwitchLib/TwitchLib.Client#31]
_This issue was originally created by [RickRosendaal](https://github.com/RickRosendaal). The issue is [here](https://github.com/swiftyspiffy/TwitchLib/issues/2)._

When creating a new client, initializing it (with or without providing a channel), calling .Connect(), and then client.JoinChannel("name"), will result into the client never joining the channel.
The following example will print "Connected". But not "Joined channel".
Removing the "client.JoinChannel" line, will print "Connected", as well as "Joined channel".
Removing the "DamnICantFly" channel parameter in the Initialize method, will again print "Connected", but not "Joined channel".

```csharp
private void Start()
{
	Client client = new Client();
	client.OnConnected += OnConnected;
	client.OnJoinedChannel += OnJoinedChannel;
	client.Initialize(new TwitchLib.Client.Models.ConnectionCredentials("DamnICantFly", "oauth_token"), "DamnICantFly");
	client.Connect();
	client.JoinChannel("LuckyNoS7evin");
}

private void OnConnected(object sender, TwitchLib.Client.Events.OnConnectedArgs e)
{
	Debug.Log("Connected");
}

private void OnJoinedChannel(object sender, TwitchLib.Client.Events.OnJoinedChannelArgs e)
{
	Debug.Log("Joined channel");
}
```

**Comment by swiftyspiffy** [comment]
So, attempting to join a channel while not connected to Twitch will result, in your case, to a JOIN command being sent but not properly received by Twitch. Understandably, the Connect is a bit confusing because while the method itself is sync, we still need to wait on a reply from Twitch to confirm a connection is established.

To fix your problem in the short term, just move `client.JoinChannel("LuckyNoS7evin")` from your Start() method, to the OnConnected method.

In the longer term, internally  we need to check if the client is actually connected and in a ready state before kicking off the join channel queue.

**Comment by RickRosendaal** [comment]
Oh. Interesting! I've never encountered this issue in the past. Makes sense though functional wise. Just a bit confusing indeed!
Breaking it like that doesn't sound intentional though. So sounds like a good idea to wait with kicking off the queue until the client is connected.

**Comment by Syzuna** [comment]
should be fixed too and can be closed I guess

**Comment by swiftyspiffy** [comment]
@Syzuna thanks for reminder

**Comment by loligans** [comment]
Definitely not fixed for me. I have to `await Task.Delay(5000)` in order to join channels because I can't `await Connect()` to ensure it completes. `OnConnected` isn't even truthful when it says "You should be connected"
